### ISSUE TITLE
E-Cell Logo 

### ISSUE THREAD

**Issue by Ritzing** [ashish0910/ecell#1]
Increase the size of the logo in the nav-bar, it is not quite visible

**Comment by Ritzing** [comment]
home - about- events(upcoming and past with cards linked to blog pages ) -Startups - Team- Testimonial - Blog- ContactUs     are the sections to be included in the nav bar

**Comment by ashish0910** [comment]
we have placed the logo at the footer since at navbar size of logo cannot be increased
